/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JLabel;
import javax.swing.JToggleButton;
import controleur.C_Abstrait;
import controleur.C_Hero;
import controleur.C_Menu;
import controleur.EnumAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;
/**
 *
 * @author btssio
 */
public class V_Hero extends V_Abstraite {
    /**
     * Creates new form V_Connexion
     */
    DefaultComboBoxModel mcbHero;
    DefaultComboBoxModel mcbFaction;
    public V_Hero(C_Abstrait ctrlAbstrait) {
        super(ctrlAbstrait);
        
       mcbHero = new DefaultComboBoxModel();
        mcbFaction = new DefaultComboBoxModel();
        
        initComponents();

        cbHero.setModel(mcbHero);
        cbFaction.setModel(mcbFaction);
    }

    /**
     *
     */
    
    public JButton getBtnImage() {
        return btnImage;
    }

    public void setBtnImage(JButton btnImage) {
        this.btnImage = btnImage;
    }

    
    public JLabel getLbImage() {
        return lbImage;
    }

    public void setLbImage(JLabel lbImage) {
        this.lbImage = lbImage;
    }

    
    public DefaultComboBoxModel getMcbFaction() {
        return mcbFaction;
    }

    public void setMcbFaction(DefaultComboBoxModel mcbFaction) {
        this.mcbFaction = mcbFaction;
    }

    
    public DefaultComboBoxModel getMcbHero() {
        return mcbHero;
    }

    public void setMcbHero(DefaultComboBoxModel mcbHero) {
        this.mcbHero = mcbHero;
    }

    
    public JButton getBtnAjouter() {
        return btnAjouter;
    }

    public void setBtnAjouter(JButton btnAjouter) {
        this.btnAjouter = btnAjouter;
    }

    public JButton getBtnNouveau() {
        return btnNouveau;
    }

    public void setBtnNouveau(JButton btnNouveau) {
        this.btnNouveau = btnNouveau;
    }

    public JButton getBtnPrecedant() {
        return btnPrecedant;
    }

    public void setBtnPrecedant(JButton btnPrecedant) {
        this.btnPrecedant = btnPrecedant;
    }

    public JButton getBtnSuivant() {
        return btnSuivant;
    }

    public void setBtnSuivant(JButton btnSuivant) {
        this.btnSuivant = btnSuivant;
    }

    public JComboBox getCbHero() {
        return cbHero;
    }

    public void setCbHero(JComboBox cbHero) {
        this.cbHero = cbHero;
    }

    public JComboBox getCbFaction() {
        return cbFaction;
    }

    public void setCbFaction(JComboBox cbFaction) {
        this.cbFaction = cbFaction;
    }

    public JTextField getTxtPtDestin() {
        return txtPtDestin;
    }

    public void setTxtPtDestin(JTextField txtPtDestin) {
        this.txtPtDestin = txtPtDestin;
    }


    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtNom() {
        return txtNom;
    }

    public void setTxtNom(JTextField txtNom) {
        this.txtNom = txtNom;
    }

    public JTextField getTxtPtForce() {
        return txtPtForce;
    }

    public void setTxtPtForce(JTextField txtPtForce) {
        this.txtPtForce = txtPtForce;
    }

    public JTextField getTxtPtMagie() {
        return txtPtMagie;
    }

    public void setTxtPtMagie(JTextField txtPtMagie) {
        this.txtPtMagie = txtPtMagie;
    }

    public JTextField getTxtPtVie() {
        return txtPtVie;
    }

    public void setTxtPtVie(JTextField txtPtVie) {
        this.txtPtVie = txtPtVie;
    }

    public JLabel getLbId() {
        return lbId;
    }

    public void setLbId(JLabel lbId) {
        this.lbId = lbId;
    }

 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGsb = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JToggleButton();
        cbHero = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPtForce = new javax.swing.JTextField();
        txtPtMagie = new javax.swing.JTextField();
        txtPtVie = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        btnNouveau = new javax.swing.JButton();
        btnPrecedant = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        cbFaction = new javax.swing.JComboBox();
        txtPtDestin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lbGsb.setText("Gestion de la BDD de Might And Magic");

        btnQuitter.setText("quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        cbHero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHeroActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        lbId.setText("id");

        jLabel4.setText("faction");

        jLabel5.setText("ListeHero");

        jLabel7.setText("point de force");

        jLabel8.setText("Point de magie");

        jLabel9.setText("point de vie");

        txtId.setText("jTextField1");

        txtPtForce.setText("jTextField1");

        txtPtMagie.setText("jTextField1");

        txtPtVie.setText("jTextField1");

        txtNom.setText("jTextField6");

        btnNouveau.setText("nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnPrecedant.setText("Précédant");
        btnPrecedant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedantActionPerformed(evt);
            }
        });

        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        cbFaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFactionActionPerformed(evt);
            }
        });

        txtPtDestin.setText("jTextField1");

        jLabel10.setText("point de destin");

        jLabel1.setText("image");

        lbImage.setText("Aucune image");

        btnImage.setText("Ajouter une image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbGsb)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addComponent(btnPrecedant)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSuivant)
                            .addGap(64, 64, 64)
                            .addComponent(btnAjouter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbId)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1))
                                            .addComponent(jLabel9)))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtId)
                                        .addComponent(txtPtForce)
                                        .addComponent(txtPtMagie)
                                        .addComponent(txtPtVie)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cbHero, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnNouveau))
                                        .addComponent(cbFaction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPtDestin, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(237, 237, 237)
                                            .addComponent(btnImage))))))))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGsb, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNouveau))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPtForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPtMagie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPtDestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPtVie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnImage))
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitter)
                    .addComponent(btnPrecedant)
                    .addComponent(btnSuivant)
                    .addComponent(btnAjouter))
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
         ((C_Hero)controleur).heroQuitter();
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnPrecedantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedantActionPerformed
        ((C_Hero)controleur).precedant();
    }//GEN-LAST:event_btnPrecedantActionPerformed

    private void cbFactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFactionActionPerformed

    private void cbHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHeroActionPerformed
        ((C_Hero)controleur).heroSelectionner();
    }//GEN-LAST:event_cbHeroActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
         ((C_Hero)controleur).suivant();
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
       ((C_Hero)controleur).nouveau();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        ((C_Hero)controleur).ajouter();
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        ((C_Hero)controleur).choixImage();
    }//GEN-LAST:event_btnImageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnPrecedant;
    private javax.swing.JToggleButton btnQuitter;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JComboBox cbFaction;
    private javax.swing.JComboBox cbHero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbGsb;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbImage;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPtDestin;
    private javax.swing.JTextField txtPtForce;
    private javax.swing.JTextField txtPtMagie;
    private javax.swing.JTextField txtPtVie;
    // End of variables declaration//GEN-END:variables
}
