/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JLabel;
import javax.swing.JToggleButton;
import controleur.C_Abstrait;
import controleur.C_Menu;
import controleur.EnumAction;
import javax.swing.DefaultListModel;
import javax.swing.JList;
/**
 *
 * @author btssio
 */
public class V_Menu extends V_Abstraite {
    /**
     * Creates new form V_Connexion
     */
    DefaultListModel mlstPartie;
    
    public V_Menu(C_Abstrait ctrlAbstrait) {
        super(ctrlAbstrait);
        initComponents();
    }

    /**
     *
     */
 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGsb = new javax.swing.JLabel();
        btnQuitter = new javax.swing.JToggleButton();
        btnListeHero = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lbGsb.setText("Gestion de la BDD de Might And Magic");

        btnQuitter.setText("quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnListeHero.setText("Liste Heros");
        btnListeHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeHeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnListeHero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbGsb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbGsb, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnListeHero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
         ((C_Menu)controleur).fichierQuitter();
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnListeHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeHeroActionPerformed
         ((C_Menu)controleur).menuHero();
    }//GEN-LAST:event_btnListeHeroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListeHero;
    private javax.swing.JToggleButton btnQuitter;
    private javax.swing.JLabel lbGsb;
    // End of variables declaration//GEN-END:variables
}
